// This file was generated by SquareLine Studio
// SquareLine Studio version: SquareLine Studio 1.6.0
// LVGL version: 8.3.11
// Project name: SquareLine_Project

#include "../ui.h"

lv_obj_t *ui_Screen2 = NULL;
lv_obj_t *ui_Image2 = NULL;
lv_obj_t *ui_Label13 = NULL;
lv_obj_t *ui_Label14 = NULL;
lv_obj_t *ui_Label15 = NULL;
lv_obj_t *ui_LabelGSM = NULL;
lv_obj_t *ui_BtnSimulate = NULL;
lv_obj_t *ui_LabelSimulate = NULL;
lv_obj_t *ui_BtnDebug = NULL;
// Settings Widgets
// (Moved to Screen 3)
// event funtions
void ui_event_Screen2(lv_event_t *e)
{
    lv_event_code_t event_code = lv_event_get_code(e);

    if (event_code == LV_EVENT_GESTURE && lv_indev_get_gesture_dir(lv_indev_get_act()) == LV_DIR_RIGHT)
    {
        lv_indev_wait_release(lv_indev_get_act());
        _ui_screen_change(&ui_Screen1, LV_SCR_LOAD_ANIM_MOVE_RIGHT, 500, 0, &ui_Screen1_screen_init);
    }
    if (event_code == LV_EVENT_GESTURE && lv_indev_get_gesture_dir(lv_indev_get_act()) == LV_DIR_LEFT)
    {
        lv_indev_wait_release(lv_indev_get_act());
        _ui_screen_change(&ui_Screen3, LV_SCR_LOAD_ANIM_MOVE_LEFT, 500, 0, &ui_Screen3_screen_init);
    }
}

// build funtions

void ui_Screen2_screen_init(void)
{
    ui_Screen2 = lv_obj_create(NULL);
    lv_obj_clear_flag(ui_Screen2, LV_OBJ_FLAG_SCROLLABLE); /// Flags
    lv_obj_set_style_bg_color(ui_Screen2, lv_color_hex(0x001220), LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_bg_opa(ui_Screen2, 255, LV_PART_MAIN | LV_STATE_DEFAULT);

    ui_Image2 = lv_img_create(ui_Screen2);
    lv_img_set_src(ui_Image2, &ui_img_logo128_png);
    lv_obj_set_width(ui_Image2, LV_SIZE_CONTENT);  /// 128
    lv_obj_set_height(ui_Image2, LV_SIZE_CONTENT); /// 128
    lv_obj_set_x(ui_Image2, 2);
    lv_obj_set_y(ui_Image2, 156);
    lv_obj_set_align(ui_Image2, LV_ALIGN_CENTER);
    lv_obj_add_flag(ui_Image2, LV_OBJ_FLAG_ADV_HITTEST);  /// Flags
    lv_obj_clear_flag(ui_Image2, LV_OBJ_FLAG_SCROLLABLE); /// Flags

    ui_Label13 = lv_label_create(ui_Screen2);
    lv_obj_set_width(ui_Label13, LV_SIZE_CONTENT);  /// 1
    lv_obj_set_height(ui_Label13, LV_SIZE_CONTENT); /// 1
    lv_obj_set_x(ui_Label13, -101);
    lv_obj_set_y(ui_Label13, 156);
    lv_obj_set_align(ui_Label13, LV_ALIGN_CENTER);
    lv_label_set_text(ui_Label13, "Life");
    lv_obj_set_style_text_font(ui_Label13, &lv_font_montserrat_36, LV_PART_MAIN | LV_STATE_DEFAULT);

    ui_Label14 = lv_label_create(ui_Screen2);
    lv_obj_set_width(ui_Label14, LV_SIZE_CONTENT);  /// 1
    lv_obj_set_height(ui_Label14, LV_SIZE_CONTENT); /// 1
    lv_obj_set_x(ui_Label14, 103);
    lv_obj_set_y(ui_Label14, 157);
    lv_obj_set_align(ui_Label14, LV_ALIGN_CENTER);
    lv_label_set_text(ui_Label14, "Link");
    lv_obj_set_style_text_font(ui_Label14, &lv_font_montserrat_36, LV_PART_MAIN | LV_STATE_DEFAULT);

    // --- DEBUG DATA ---
    ui_Label06 = lv_label_create(ui_Screen2);
    lv_obj_set_width(ui_Label06, LV_SIZE_CONTENT);
    lv_obj_set_height(ui_Label06, LV_SIZE_CONTENT);
    lv_obj_set_x(ui_Label06, 0);
    lv_obj_set_y(ui_Label06, -190);
    lv_obj_set_align(ui_Label06, LV_ALIGN_CENTER);
    lv_label_set_text(ui_Label06, "DEBUG SENSORS");

    // X Row
    ui_Label03 = lv_label_create(ui_Screen2);
    lv_obj_set_align(ui_Label03, LV_ALIGN_CENTER);
    lv_label_set_text(ui_Label03, "X:");
    lv_obj_set_x(ui_Label03, -100);
    lv_obj_set_y(ui_Label03, -120);

    ui_LabelX = lv_label_create(ui_Screen2);
    lv_obj_set_align(ui_LabelX, LV_ALIGN_CENTER);
    lv_label_set_text(ui_LabelX, "0.00");
    lv_obj_set_x(ui_LabelX, -40);
    lv_obj_set_y(ui_LabelX, -120);

    // Y Row
    ui_Label04 = lv_label_create(ui_Screen2);
    lv_obj_set_align(ui_Label04, LV_ALIGN_CENTER);
    lv_label_set_text(ui_Label04, "Y:");
    lv_obj_set_x(ui_Label04, -100);
    lv_obj_set_y(ui_Label04, -80);

    ui_LabelY = lv_label_create(ui_Screen2);
    lv_obj_set_align(ui_LabelY, LV_ALIGN_CENTER);
    lv_label_set_text(ui_LabelY, "0.00");
    lv_obj_set_x(ui_LabelY, -40);
    lv_obj_set_y(ui_LabelY, -80);

    // Z Row
    ui_Label05 = lv_label_create(ui_Screen2);
    lv_obj_set_align(ui_Label05, LV_ALIGN_CENTER);
    lv_label_set_text(ui_Label05, "Z:");
    lv_obj_set_x(ui_Label05, -100);
    lv_obj_set_y(ui_Label05, -40);

    ui_LabelZ = lv_label_create(ui_Screen2);
    lv_obj_set_align(ui_LabelZ, LV_ALIGN_CENTER);
    lv_label_set_text(ui_LabelZ, "0.00");
    lv_obj_set_x(ui_LabelZ, -40);
    lv_obj_set_y(ui_LabelZ, -40);

    // G Total
    ui_LabelG = lv_label_create(ui_Screen2);
    lv_obj_set_align(ui_LabelG, LV_ALIGN_CENTER);
    lv_label_set_text(ui_LabelG, "G: 0.00");
    lv_obj_set_x(ui_LabelG, 0);
    lv_obj_set_y(ui_LabelG, 0);
    lv_obj_set_style_text_font(ui_LabelG, &lv_font_montserrat_36, LV_PART_MAIN | LV_STATE_DEFAULT);

    // --- GSM STATUS ---
    ui_LabelGSM = lv_label_create(ui_Screen2);
    lv_obj_set_align(ui_LabelGSM, LV_ALIGN_CENTER);
    lv_label_set_text(ui_LabelGSM, "GSM: --");
    lv_obj_set_x(ui_LabelGSM, 0);
    lv_obj_set_y(ui_LabelGSM, -165); // Just below "DEBUG SENSORS"
    lv_obj_set_style_text_color(ui_LabelGSM, lv_color_hex(0x00AAFF), LV_PART_MAIN);
    lv_obj_set_style_text_font(ui_LabelGSM, &lv_font_montserrat_16, LV_PART_MAIN);

    // Gyro
    // (Switches moved to Screen 3)

    // --- BUTTON DEBUG ---
    ui_BtnDebug = lv_btn_create(ui_Screen2);
    lv_obj_set_width(ui_BtnDebug, 110);
    lv_obj_set_height(ui_BtnDebug, 40);
    lv_obj_set_x(ui_BtnDebug, -60);
    lv_obj_set_y(ui_BtnDebug, 70); // Placed above the logo
    lv_obj_set_align(ui_BtnDebug, LV_ALIGN_CENTER);
    lv_obj_add_flag(ui_BtnDebug, LV_OBJ_FLAG_CHECKABLE | LV_OBJ_FLAG_SCROLL_ON_FOCUS);
    lv_obj_clear_flag(ui_BtnDebug, LV_OBJ_FLAG_SCROLLABLE);
    lv_obj_set_style_bg_color(ui_BtnDebug, lv_color_hex(0x3A5A7A), LV_PART_MAIN | LV_STATE_DEFAULT); // Gray-blue
    lv_obj_set_style_bg_color(ui_BtnDebug, lv_color_hex(0x00AA00), LV_PART_MAIN | LV_STATE_CHECKED); // Green when active

    lv_obj_t *ui_LabelDebugBtn = lv_label_create(ui_BtnDebug);
    lv_obj_set_width(ui_LabelDebugBtn, LV_SIZE_CONTENT);
    lv_obj_set_height(ui_LabelDebugBtn, LV_SIZE_CONTENT);
    lv_obj_set_align(ui_LabelDebugBtn, LV_ALIGN_CENTER);
    lv_label_set_text(ui_LabelDebugBtn, "DEBUG");
    lv_obj_set_style_text_font(ui_LabelDebugBtn, &lv_font_montserrat_14, LV_PART_MAIN | LV_STATE_DEFAULT);

    // --- BUTTON SIMULATE FALL ---
    ui_BtnSimulate = lv_btn_create(ui_Screen2);
    lv_obj_set_width(ui_BtnSimulate, 110);
    lv_obj_set_height(ui_BtnSimulate, 40);
    lv_obj_set_x(ui_BtnSimulate, 60);
    lv_obj_set_y(ui_BtnSimulate, 70); // Placed above the logo
    lv_obj_set_align(ui_BtnSimulate, LV_ALIGN_CENTER);
    lv_obj_add_flag(ui_BtnSimulate, LV_OBJ_FLAG_SCROLL_ON_FOCUS);
    lv_obj_clear_flag(ui_BtnSimulate, LV_OBJ_FLAG_SCROLLABLE);
    lv_obj_set_style_bg_color(ui_BtnSimulate, lv_color_hex(0xFF0000), LV_PART_MAIN | LV_STATE_DEFAULT); // Red button

    ui_LabelSimulate = lv_label_create(ui_BtnSimulate);
    lv_obj_set_width(ui_LabelSimulate, LV_SIZE_CONTENT);
    lv_obj_set_height(ui_LabelSimulate, LV_SIZE_CONTENT);
    lv_obj_set_align(ui_LabelSimulate, LV_ALIGN_CENTER);
    lv_label_set_text(ui_LabelSimulate, "Simuliraj!");
    lv_obj_set_style_text_font(ui_LabelSimulate, &lv_font_montserrat_14, LV_PART_MAIN | LV_STATE_DEFAULT);

    // Add Event listener to button to open Screen 4
    lv_obj_add_event_cb(ui_BtnSimulate, btn_simulate_fall_cb, LV_EVENT_ALL, NULL);

    lv_obj_add_event_cb(ui_Screen2, ui_event_Screen2, LV_EVENT_ALL, NULL);
}

void ui_Screen2_screen_destroy(void)
{
    if (ui_Screen2)
        lv_obj_del(ui_Screen2);

    // NULL screen variables
    ui_Screen2 = NULL;
    ui_Image2 = NULL;
    ui_Label13 = NULL;
    ui_Label14 = NULL;
    ui_Label15 = NULL;
    ui_LabelGSM = NULL;
    ui_BtnSimulate = NULL;
    ui_LabelSimulate = NULL;
    ui_BtnDebug = NULL;
}
