// This file was generated by SquareLine Studio
// SquareLine Studio version: SquareLine Studio 1.6.0
// LVGL version: 8.3.11
// Project name: SquareLine_Project

#ifndef _SQUARELINE_PROJECT_UI_H
#define _SQUARELINE_PROJECT_UI_H

#ifdef __cplusplus
extern "C"
{
#endif

#include "lvgl.h"

#include "ui_helpers.h"
#include "ui_events.h"

    ///////////////////// SCREENS ////////////////////

#include "screens/ui_Screen1.h"
#include "screens/ui_Screen2.h"

    ///////////////////// VARIABLES ////////////////////
    extern lv_obj_t *ui_LabelTime;

    // EVENTS

    extern lv_obj_t *ui____initial_actions0;

    // IMAGES AND IMAGE SETS
    LV_IMG_DECLARE(ui_img_logo128_png); // assets/logo128.png
    LV_IMG_DECLARE(ui_img_pulse36_png); // assets/pulse36.png
    LV_IMG_DECLARE(ui_img_1716151603);  // assets/spo2-36.png

    // UI INIT
    void ui_init(void);
    void ui_destroy(void);

#ifdef __cplusplus
} /*extern "C"*/
#endif

#endif
